-- =====================================================
-- ĐỔI COLLATION CHO CÁC CỘT TEXT (BỎ QUA PK/FK)
-- Database: course-survey-db
-- Target collation: Vietnamese_CI_AS_WS
-- =====================================================

ALTER TABLE DIM_CAU_HOI ALTER COLUMN NoiDung NVARCHAR(MAX) COLLATE Vietnamese_CI_AS_WS;
ALTER TABLE DIM_CAU_HOI ALTER COLUMN Phan VARCHAR(20) COLLATE Vietnamese_CI_AS_WS;
ALTER TABLE DIM_CAU_HOI ALTER COLUMN LoaiTraLoi VARCHAR(20) COLLATE Vietnamese_CI_AS_WS;
GO

ALTER TABLE DIM_KHOA ALTER COLUMN TenKhoa VARCHAR(100) COLLATE Vietnamese_CI_AS_WS;
GO

ALTER TABLE DIM_CHUYEN_NGANH ALTER COLUMN TenChuyenNganh VARCHAR(100) COLLATE Vietnamese_CI_AS_WS;
GO

ALTER TABLE DIM_CHUONG_TRINH_DAO_TAO ALTER COLUMN TenCTDT VARCHAR(100) COLLATE Vietnamese_CI_AS_WS;
GO

ALTER TABLE DIM_LOP_SINH_VIEN ALTER COLUMN Lop VARCHAR(20) COLLATE Vietnamese_CI_AS_WS;
GO

ALTER TABLE DIM_SINH_VIEN ALTER COLUMN HoDem VARCHAR(50) COLLATE Vietnamese_CI_AS_WS;
ALTER TABLE DIM_SINH_VIEN ALTER COLUMN Ten VARCHAR(50) COLLATE Vietnamese_CI_AS_WS;
GO

ALTER TABLE DIM_GIANG_VIEN ALTER COLUMN HoDemGV VARCHAR(50) COLLATE Vietnamese_CI_AS_WS;
ALTER TABLE DIM_GIANG_VIEN ALTER COLUMN TenGV VARCHAR(50) COLLATE Vietnamese_CI_AS_WS;
GO

ALTER TABLE DIM_HOC_PHAN ALTER COLUMN TenHP VARCHAR(100) COLLATE Vietnamese_CI_AS_WS;
GO

ALTER TABLE DIM_HOC_KY ALTER COLUMN NamHoc VARCHAR(9) COLLATE Vietnamese_CI_AS_WS;
GO

ALTER TABLE DIM_LOP_HOC_PHAN ALTER COLUMN LopHP VARCHAR(100) COLLATE Vietnamese_CI_AS_WS;
GO

ALTER TABLE FACT_TRA_LOI_KHAO_SAT ALTER COLUMN TraLoiText TEXT COLLATE Vietnamese_CI_AS_WS;
GO
