-- Xóa theo đúng thứ tự quan hệ

DELETE FROM FACT_KET_QUA_DANH_GIA;
DELETE FROM FACT_GOP_Y_TU_LUAN;
DELETE FROM DIM_LOP_HOC_PHAN;
DELETE FROM DIM_SINH_VIEN;
DELETE FROM DIM_LOP_SINH_VIEN;  
DELETE FROM DIM_CHUYEN_NGANH;
DELETE FROM DIM_NGANH;
DELETE FROM DIM_HOC_PHAN;
DELETE FROM DIM_GIANG_VIEN;
DELETE FROM DIM_HOC_KY;
DELETE FROM DIM_KHOA;
