name: Survey ETL Pipeline

on:
  workflow_dispatch:
    inputs:
      semester:
        description: 'Năm học (VD: 2024-2025)'
        required: true
        default: '2024-2025'
        type: string
      survey_file:
        description: 'Tên file (VD: khaosat_252.csv)'
        required: true
        default: 'khaosat_252.csv'
        type: string

jobs:
  etl:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      PYTHONIOENCODING: utf-8
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Microsoft ODBC Driver 18
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
          
      - name: Install dependencies
        run: |
          pip install pandas
          pip install azure-storage-blob
          pip install ftfy
          pip install sqlalchemy pyodbc
      
      - name: Step 1 - Run ETL
        run: python etl.py
        env:
          SEMESTER: ${{ github.event.inputs.semester }}
          SURVEY_FILE: ${{ github.event.inputs.survey_file }}
          CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}


      - name: Step 2 - Load to SQL
        run: python load_to_sql.py
